### PR TITLE
Simplify build, update dependencies, add PSA about -Dlog4j.skipJansi=false

### PR DESCRIPTION
**Pull request by Fourmisain**
When I recently started my 1.17 server I was wondering why the log output wasn't using any colors anymore (except for the syntax highlighting) and at first I thought there was an issue with jline4mcdsrv, but as it turns out, Mojang updated Log4J2 and Jansi [isn't used by default anymore](https://issues.apache.org/jira/browse/LOG4J2-2087), so now `-Dlog4j.skipJansi=false` is required to get styled log output.
(And it also seems it is currently [not possible](https://issues.apache.org/jira/browse/LOG4J2-2164) to programmatically enable this, I tried.)

So while looking at jline4mcdsrv I simplified the gradle build a bunch (now that I have some idea of what I'm doing) and updated everything.

## Changes

- all version numbers (including dependencies and the mod version from `fabric.mod.json`) are now found in `gradle.properties`
- update jline/terminal-jansi to 3.20.0 (from 3.15.0), jansi to 2.3.3 (from 1.18)
- remove unnecessary and deprecated repositories (loom already adds the most important ones)
- remove unused `provided` configuration and `zipTree` (https://github.com/chirs241097/jline4mcdsrv/commit/810708ea6e04a05f644c8468e5ffef1cd8745505 replaced this with `modImplementation include()`)
- replace `task sourcesJar` with `withSourcesJar()` from the "java" gradle plugin (which loom includes)
- update gradle version to ~~7.1.1~~ 7.2, run `gradlew wrapper` to update wrapper files
- update to loom 0.9
- fix a deprecated constructor call and enable `-Xlint:deprecation` compiler flag for easier future proofing
- update `README` to add PSA about `-Dlog4j.skipJansi=false`
- bump version to 0.2.1

Also, I noticed the CurseForge page says jline4mcdsrv requires fabric api since 0.1.0. That isn't actually true!
No version of jline4mcdsrv requires to install fabric api. auto-config internally depends on fabric api but it also included that part in the built jar. With the [switch to cloth-config](https://github.com/chirs241097/jline4mcdsrv/commit/810708ea6e04a05f644c8468e5ffef1cd8745505) even that internal fabric api use is gone.

**edit**: For a few more changes see https://github.com/chirs241097/jline4mcdsrv/pull/12#issuecomment-906420492

### CODE REVIEW

**Comment by Fourmisain** [comment]
**edit**: Not relevant anymore.

I ran into a small issue where parts of my configuration would be lost after jline4mcdsrv is finished loading, e.g. I often add stuff like
```
<Logger name="loggername" level="debug"></Logger>
```
to set/increase the log level or
```
<Logger name="loggername">
	<Filters>
		<LevelRangeFilter minLevel="INFO" maxLevel="INFO" onMatch="DENY" onMismatch="NEUTRAL" />
	</Filters>
</Logger>
```
to shut up certain loggers due to log spam.

I can't claim to fully understand why but adding a `ctx.reconfigure();` before `ctx.updateLoggers();` seemed to have solved this issue - at least for setting the log levels, so I added this fix as well.

**Comment by wb1016** [comment]
still not getting color with command:
`java -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -Dlog4j.skipJansi=false -jar fabric-server-launch.jar -nogui`

**Comment by Fourmisain** [comment]
Oh, you're right!
I only got color because of my custom log4j2 config file - I use that via `-Dlog4j.configurationFile=log4j2.xml` to set the same log pattern as in `jline4mcdsrv.toml` so that everything is colored from the very beginning, not only after jline4mcdsrv actually starts.

I'll look into why it won't apply the pattern by itself.

**Comment by Fourmisain** [comment]
I removed the `ctx.reconfigure();` again, so now it should work as before - but only with the vanilla log4j2 config.

I'm still trying to figure out how to properly modify the config programmatically so it doesn't lose any custom configuration.

Going by the vanilla log4j2.xml file:
```
...
<Appenders>
  <Console name="SysOut" target="SYSTEM_OUT">
    ...
  </Console>
</Appenders>
<Loggers>
  ...
  some logger configurations
  ...
  <Root level="info">
    ...
    <AppenderRef ref="SysOut"/>
...
```
In theory it should be as simple as replacing the vanilla SysOut Console appender with jline4mcdsrv's ConsoleAppender and giving it the same name.
The root logger should give it's output to it and everything should be fine, but since this is log4j2 we are talking about, nothing works as expected...

**Comment by Fourmisain** [comment]
Okay, finally figured it out!

The issues with my config seemingly not being applied were completely my fault:
 - I was using shorted logger names, e.g. `class_2170` instead of `net.minecraft.class_2170` in the case of trying to disable certain loggers
 - In the case of enabling debug level logging, I was accidentally using the wrong `LOGGER` instance (some Minecraft classes have their own logger and I was trying to debug a mixin into such a class), so `LOGGER.debug()` would just get filtered out

So nothing actually broke - I still see some small room for improvement though, so I'll probably make another small commit.

**Comment by Fourmisain** [comment]
To comment on the last few commits (which should really be the last ones, this is already getting too big):

- Log4j2 core already has a `ConsoleAppender`, so I renamed jline4mcdsrv's one to something more meaningful.
- Changing the root logger config instead should be just a tiny bit more compatible and the code gets a little easier.
- The `.gitattributes` will ensure that the repo always contains LF line endings (LF normalization) and everyone cloning/checking out will have their own choice of whether they want CRLF or LF endings (via git's `core.eol` setting).
- It's been so long that I updated to even newer gradle and loom

**Comment by wb1016** [comment]
now all working as intended without deprecated function! thanks.

**Comment by chirs241097** [comment]
Sorry for overlooking the pull requests. I hardly ever check github notifications these days...

Thank you wonderful people for your generous contribution. I'm considering to give some of you collaborator access to this repository (as well as the curseforge project), mainly because I don't have much time (or enough mental capacity) to work on a minecraft mod. For some reason I'm completely fine with C++, but even the tiniest touch of Java will drive me nuts. If you're interested, please reply here or shoot me an email.

**Comment by Fourmisain** [comment]
I'd like to maintain it!
In a sense I'm already doing that anyway, collaboration access would just make this easier.
This would also not be my first time, I'm currently (officially) maintaining [Falling Leaves](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric), [Chat Heads](https://www.curseforge.com/minecraft/mc-mods/chat-heads) and [IndyPets](https://www.curseforge.com/minecraft/mc-mods/indypets) and inofficially maintaining a bunch of other mods, on top of my own.

For CurseForge you could give me the "Maintainer" role.
I think the only permissions I actually need are "Manage Files" and "Edit Description" (the latter because I'd like to add the PSA about `-Dlog4j.skipJansi=false`).
I never found out what all these other permissions actually do... "Access Repository"? "View Insights"? "Manage Pages"? No idea.

P.S. I rebased this PR and updated some more stuff - the mod should be compatible with 1.17 too, though I think it won't actually work because it includes a Cloth Config version for 1.18.
P.P.S. The mod does run on 1.17 too if Cloth Config is installed manually

**Comment by chirs241097** [comment]
@Fourmisain I've got you covered! Collaborator invitation sent.

**Comment by Fourmisain** [comment]
Great!
First thing I'll probably replace the huge Cloth Config dependency with straight toml4j so it's more compatible with different Minecraft versions.
I actually already did this, just need to do some more testing.

**Pull request merged**
