### PR TITLE
Config for styling compatibility background; obfuscation fix; debugging instructions

### PR DESCRIPTION
**Pull request by vlad2305m**
Screenshot_20230119_123304
Screenshot_20230119_123232
Backgroud off:
Screenshot_20230119_125345

I use AlterierHeath.light theme with [Konsole](https://konsole.kde.org/) on [Arch](https://archlinux.org/). Moved to linux a few months ago and it works much better than Windows.

### CODE REVIEW

**Comment by cs127** [comment]
In my opinion, `\033[5m` is not the best choice for `§k`, because unlike in Minecraft, the text is readable.

I think `\033[8m` was better. Even though it's not supported by some terminal emulators, its intended behavior is closer to that of `§k` in Minecraft.

Or you could add a configurable option in the config file to set whether it should use `\033[5m` or `\033[8m`.

**Comment by Fourmisain** [comment]
PR is looking good!

> In my opinion, \033[5m is not the best choice for §k, because unlike in Minecraft, the text is readable.

Hm... I'm pretty neutral about that, because only the server owner has access to the console, but the server owner would surely already know the hidden text, right?
Personally I'd probably be more annoyed at the fact that the text is blinking at me like those ancient gif ad banners 😄

So yeah, a config option wouldn't be a bad idea, maybe something like a `concealObfuscatedText` boolean?

**Comment by cs127** [comment]
> So yeah, a config option wouldn't be a bad idea, maybe something like a `concealObfuscatedText` boolean?

Sure, sounds great!

**Comment by Fourmisain** [comment]
Gonna wait for feedback from vlad before I merge and add the config option, just to make sure we're all on the same page.

**Comment by vlad2305m** [comment]
Definitely add the config! Just don't set it to char 8 by default as it
replaces text by white space for linux users

**Comment by Fourmisain** [comment]
There we go 7d9026a9026fcef936db6572ae0ab9dad31a6554, new version 0.4.2 is up.
Couldn't test it, but I think I got those 2 lines correct.

**Pull request merged**
